<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PayServices" nsURI="http://www.uniandes.edu.co/payServices"
    nsPrefix="PayServices">
  <eClassifiers xsi:type="ecore:EClass" name="EntidadNegocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aportes" upperBound="-1"
        eType="#//Aporte" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperEntidad">
    <eOperations name="obtenerEntidadNegocio"/>
    <eOperations name="modificarEntidadNegocio"/>
    <eOperations name="obtenerEntidadesNegocio"/>
    <eOperations name="eliminarEntidadNegocio"/>
    <eOperations name="crearEntidadNegocio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidadesNegocio" upperBound="-1"
        eType="#//EntidadNegocio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pagos" upperBound="-1"
        eType="#//Pago" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="novedades" upperBound="-1"
        eType="#//Novedad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Atributo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" lowerBound="1" eType="#//Valor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constante" eSuperTypes="#//Atributo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" lowerBound="1" eType="#//Valor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionArimetica" eSuperTypes="#//Operandos">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operandoIzq" lowerBound="1"
        eType="#//Operandos" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operandoDer" lowerBound="1"
        eType="#//Operandos" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operador" lowerBound="1"
        eType="#//Operador" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operandos" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Valor" abstract="true" eSuperTypes="#//Operandos">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clase" eType="#//Clase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operador">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simbolo" eType="#//Operadores"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aplicaSobre" lowerBound="1"
        eType="#//Atributo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculoAporte" lowerBound="1"
        eType="#//CalculoAporte" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condicion" eType="#//Condiciones"
        defaultValueLiteral="IGUAL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="novedad" eType="#//Novedad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valorComparar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aplica" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valorParaCalculo" lowerBound="1"
        eType="#//Valor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultadoValidacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperadorServicio">
    <eOperations name="crearSuperEntidadNegocio"/>
    <eOperations name="modificarSuperEntidadNegocio"/>
    <eOperations name="eliminarSuperEntidadNegocio"/>
    <eOperations name="obtenerSuperEntidadesNegocio"/>
    <eOperations name="obtenerSuperEntidadNegocio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superEntidades" upperBound="-1"
        eType="#//SuperEntidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bancos" upperBound="-1"
        eType="#//Banco" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiposNovedad" upperBound="-1"
        eType="#//TipoNovedad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clasesValores" upperBound="-1"
        eType="#//Clase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Novedad">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaCreacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaInicio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaFin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoNovedad" lowerBound="1"
        eType="#//TipoNovedad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoNovedad">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aporte">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validaciones" upperBound="-1"
        eType="#//Validacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculoAporte">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expresionArimetica" lowerBound="1"
        eType="#//ExpresionArimetica" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultado" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Banco">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pagos" eType="#//Pago"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pago">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculoAportes" upperBound="-1"
        eType="#//CalculoAporte" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Condiciones">
    <eLiterals name="IGUAL"/>
    <eLiterals name="DIFERENTE" value="1"/>
    <eLiterals name="MENOR_IGUAL" value="2"/>
    <eLiterals name="MAYOR_IGUAL" value="3"/>
    <eLiterals name="MENOR" value="4"/>
    <eLiterals name="MAYOR" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoTexto" eSuperTypes="#//Valor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoEntero" eSuperTypes="#//Valor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoDecimal" eSuperTypes="#//Valor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoBooleano" eSuperTypes="#//Valor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operadores">
    <eLiterals name="+"/>
    <eLiterals name="-" value="1"/>
    <eLiterals name="*" value="2"/>
    <eLiterals name="/" value="3"/>
  </eClassifiers>
</ecore:EPackage>
